version: '3.6'

services:

  domino:

    image: ${CONTAINER_IMAGE}
    container_name: ${CONTAINER_NAME}
    hostname: ${CONTAINER_HOSTNAME}
    stop_grace_period: 120s

    environment:
      LANG: en_US.UTF-8      

    cap_add:
      - SYS_PTRACE

    ports:
      - 1353:1352
      - 80:80
      - 443:443

    volumes:
      - domino_vol:/local 

    networks:
      server_net:

volumes:

  domino_vol:
    name: domino_local
    external: false

networks:

  server_net:
    driver: bridge
