ARG BASE_IMAGE
FROM $BASE_IMAGE

ARG DownloadFrom=
ARG LinuxYumUpdate=
ARG SPECIAL_CURL_ARGUMENTS=

USER root

COPY install_dir /tmp/install_dir

HEALTHCHECK --interval=60s --timeout=10s CMD /healthcheck.sh

RUN /tmp/install_dir/install.sh && \
  rm -rf /tmp/install_dir

# Exposed ports are inherited from base image by default

#EXPOSE 1352 80 110 143 389 443 636 993 995

USER 1000
